services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_FIREBASE_KEY: ${FIREBASE_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_SENDER_ID: ${FIREBASE_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    environment:
      VITE_FIREBASE_KEY: ${FIREBASE_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_SENDER_ID: ${FIREBASE_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    ports:
      - "80:8000"
      - "443:8000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
